INSERT INTO owners (name, age) VALUES ('Donald', 29);
INSERT INTO owners (name, age) VALUES ('John', 33);
INSERT INTO owners (name, age) VALUES ('Jane', 43);
INSERT INTO owners (name, age) VALUES ('Yuki', 67);
INSERT INTO owners (name, age) VALUES ('Erin', 21);
INSERT INTO owners (name, age) VALUES ('Siobhan', 55);
INSERT INTO owners (name, age) VALUES ('Samwise', 55);
INSERT INTO owners (name, age) VALUES ('Meriadoc', 40);
INSERT INTO owners (name, age) VALUES ('Peregrin', 39);
INSERT INTO properties (name, units, owner_id) VALUES ('Archstone', 20, 7);
INSERT INTO properties (name, units, owner_id) VALUES ('Zenith Hills', 10, 2);
INSERT INTO properties (name, units, owner_id) VALUES ('Willowspring', 30, 1);
INSERT INTO properties (name, units, owner_id) VALUES ('Ridgefield Bay', 5, 4);
INSERT INTO properties (name, units, owner_id) VALUES ('Brookvista', 20, 7);
INSERT INTO properties (name, units, owner_id) VALUES ('Goldendale', 15, 6);
INSERT INTO properties (name, units, owner_id) VALUES ('Green Haven', 40, 8);
INSERT INTO properties (name, units, owner_id) VALUES ('Fair Creek', 35, 9);
INSERT INTO properties (name, units, owner_id) VALUES ('Parkview Pointe', 50, 7);
INSERT INTO properties (name, units, owner_id) VALUES ('Royal Gardens Court', 45, 3);
INSERT INTO properties (name, units, owner_id) VALUES ('Taren Ferry', 60, 7);
INSERT INTO properties (name, units, owner_id) VALUES ('Bag End', 1, 8);
INSERT INTO properties (name, units, owner_id) VALUES ('Underhill', 10, 4);