INSERT INTO owners (name, age) VALUES ('Donald', 29);
INSERT INTO owners (name, age) VALUES ('John', 33);
INSERT INTO owners (name, age) VALUES ('Jane', 43);
INSERT INTO owners (name, age) VALUES ('Yuki', 67);
INSERT INTO owners (name, age) VALUES ('Erin', 21);
INSERT INTO owners (name, age) VALUES ('Siobhan', 55);
INSERT INTO owners (name, age) VALUES ('Kevin', 30);
INSERT INTO owners (name, age) VALUES ('Josie', 26);
INSERT INTO owners (name, age) VALUES ('Archer', 35);

INSERT INTO properties (name, units, owner_id) VALUES ('Archstone', 20, 7);
INSERT INTO properties (name, units, owner_id) VALUES ('Zenith Hills', 10, 4);
INSERT INTO properties (name, units, owner_id) VALUES ('Willowspring', 30, 5);
INSERT INTO properties (name, units, owner_id) VALUES ('Ridgefield Bay', 5, 1);
INSERT INTO properties (name, units, owner_id) VALUES ('Brookvista', 20, 5);
INSERT INTO properties (name, units, owner_id) VALUES ('Goldendale', 15, 3);
INSERT INTO properties (name, units, owner_id) VALUES ('Green Haven', 40, 2);
INSERT INTO properties (name, units, owner_id) VALUES ('Fair Creek', 35, 9);
INSERT INTO properties (name, units, owner_id) VALUES ('Parkview Pointe', 50, 6);
INSERT INTO properties (name, units, owner_id) VALUES ('Royal Gardens Court', 45, 7);
INSERT INTO properties (name, units, owner_id) VALUES ('Arbor Heights', 38, 2);
INSERT INTO properties (name, units, owner_id) VALUES ('River Bluff', 27, 8);
INSERT INTO properties (name, units, owner_id) VALUES ('Canyon Creek', 20, 9);
